import pytest
from django.apps import apps
from django.contrib.auth.models import User
from rest_framework.test import APIClient

from api.models import ClayBody, GlazeType, Tag
from api.serializer_registry import _GLOBAL_ENTRY_SERIALIZERS


def _get_serializer(model_name: str):
    model_cls = apps.get_model('api', model_name)
    return _GLOBAL_ENTRY_SERIALIZERS[model_cls]


@pytest.mark.django_db
class TestAutoGeneratedTagSerializer:
    def test_serializes_private_tag(self):
        TagSerializer = _get_serializer('Tag')
        user = User.objects.create(username='taguser@example.com', email='taguser@example.com')
        tag = Tag.objects.create(user=user, name='personal')
        data = TagSerializer(tag).data
        assert data['name'] == 'personal'
        assert data['is_public'] is False
        assert isinstance(data['id'], str)

    def test_color_field_present(self):
        TagSerializer = _get_serializer('Tag')
        user = User.objects.create(username='coloruser@example.com', email='coloruser@example.com')
        tag = Tag.objects.create(user=user, name='teal', color='#008080')
        data = TagSerializer(tag).data
        assert data['color'] == '#008080'

    def test_globals_endpoint_returns_tags_with_correct_shape(self):
        user = User.objects.create(username='tagapi@example.com', email='tagapi@example.com')
        Tag.objects.create(user=user, name='ocean', color='#0000ff')
        c = APIClient()
        c.force_authenticate(user=user)
        resp = c.get('/api/globals/tag/')
        assert resp.status_code == 200
        items = resp.json()
        assert len(items) == 1
        assert items[0]['name'] == 'ocean'
        assert items[0]['color'] == '#0000ff'
        assert items[0]['is_public'] is False
        assert isinstance(items[0]['id'], str)


@pytest.mark.django_db
class TestAutoGeneratedClayBodySerializer:
    def test_short_description_included(self):
        ClayBodySerializer = _get_serializer('ClayBody')
        user = User.objects.create(username='cbuser@example.com', email='cbuser@example.com')
        cb = ClayBody.objects.create(user=user, name='Stoneware', short_description='High-fire gray')
        data = ClayBodySerializer(cb).data
        assert data['name'] == 'Stoneware'
        assert data['short_description'] == 'High-fire gray'
        assert data['is_public'] is False
        assert isinstance(data['id'], str)

    def test_globals_endpoint_includes_short_description(self):
        user = User.objects.create(username='cbapi@example.com', email='cbapi@example.com')
        ClayBody.objects.create(user=user, name='Porcelain', short_description='Translucent')
        c = APIClient()
        c.force_authenticate(user=user)
        resp = c.get('/api/globals/clay_body/')
        assert resp.status_code == 200
        items = resp.json()
        assert len(items) == 1
        assert items[0]['short_description'] == 'Translucent'


@pytest.mark.django_db
class TestAutoGeneratedGlazeTypeSerializer:
    def test_extra_fields_included(self):
        GlazeTypeSerializer = _get_serializer('GlazeType')
        gt = GlazeType.objects.create(
            user=None, name='Celadon', short_description='Pale green', test_tile_image=''
        )
        data = GlazeTypeSerializer(gt).data
        assert data['name'] == 'Celadon'
        assert data['short_description'] == 'Pale green'
        assert data['is_public'] is True
        assert isinstance(data['id'], str)

    def test_globals_endpoint_includes_extra_fields(self):
        GlazeType.objects.create(user=None, name='Tenmoku', short_description='Iron black')
        user = User.objects.create(username='gtapi@example.com', email='gtapi@example.com')
        c = APIClient()
        c.force_authenticate(user=user)
        resp = c.get('/api/globals/glaze_type/')
        assert resp.status_code == 200
        items = resp.json()
        assert len(items) == 1
        assert items[0]['short_description'] == 'Iron black'


@pytest.mark.django_db
class TestGlobalEntries:
    def test_piece_global_uses_registered_rich_serializer_without_glaze_hack(
        self, client, piece
    ):
        response = client.get('/api/globals/piece/')

        assert response.status_code == 200
        assert response.json() == [
            {
                'id': str(piece.id),
                'name': 'Test Bowl',
                'created': piece.created.isoformat().replace('+00:00', 'Z'),
                'last_modified': piece.last_modified.isoformat().replace(
                    '+00:00', 'Z'
                ),
                'thumbnail': None,
                'current_state': {'state': 'designed'},
                'current_location': None,
                'tags': [],
            }
        ]

    def test_all_factory_globals_have_registered_serializer(self):
        from api.workflow import get_global_config, get_global_names, is_factory_global
        for global_name in get_global_names():
            if not is_factory_global(global_name):
                continue
            model_name = get_global_config(global_name)['model']
            model_cls = apps.get_model('api', model_name)
            assert model_cls in _GLOBAL_ENTRY_SERIALIZERS, (
                f'{global_name} ({model_name}) has no registered entry serializer'
            )
