"""Tests for the GlobalModel factory functions.

Verifies that _make_simple_global_model and _make_compose_global_models
generate classes with the correct fields, constraints, and helpers — without
requiring DB access.  Migration-compatibility of the three converted simple
globals (Location, ClayBody, GlazeMethod) is validated by running
`manage.py makemigrations --check` in CI.
"""
import pytest
from django.db import models


# ---------------------------------------------------------------------------
# _dsl_field_to_django_field
# ---------------------------------------------------------------------------

class TestDslFieldToDjangoField:
    """Unit tests for the DSL field → Django field mapping helper."""

    def _call(self, field_name: str, field_def: dict):
        from api.models import _dsl_field_to_django_field
        return _dsl_field_to_django_field(field_name, field_def)

    def test_name_field_is_char255_no_blank(self):
        f = self._call('name', {'type': 'string'})
        assert isinstance(f, models.CharField)
        assert f.max_length == 255
        assert not f.blank

    def test_string_field_is_char1024_blank(self):
        f = self._call('short_description', {'type': 'string'})
        assert isinstance(f, models.CharField)
        assert f.max_length == 1024
        assert f.blank

    def test_image_field_is_char1024_blank(self):
        f = self._call('test_tile_image', {'type': 'image'})
        assert isinstance(f, models.CharField)
        assert f.max_length == 1024
        assert f.blank

    def test_enum_field_uses_choices_and_capped_max_length(self):
        f = self._call('cone', {'type': 'string', 'enum': ['04', '6', '10']})
        assert isinstance(f, models.CharField)
        assert f.max_length == 16   # max(2, 16)
        assert f.choices == [('04', '04'), ('6', '6'), ('10', '10')]

    def test_integer_field(self):
        f = self._call('temperature_c', {'type': 'integer'})
        assert isinstance(f, models.IntegerField)
        assert f.null and f.blank

    def test_number_field(self):
        f = self._call('weight_grams', {'type': 'number'})
        assert isinstance(f, models.FloatField)
        assert f.null and f.blank

    def test_boolean_field_is_nullable(self):
        f = self._call('is_food_safe', {'type': 'boolean'})
        assert isinstance(f, models.BooleanField)
        assert f.null and f.blank

    def test_unknown_type_falls_back_to_json(self):
        f = self._call('data', {'type': 'object'})
        assert isinstance(f, models.JSONField)

    def test_max_length_overrides_default(self):
        f = self._call('atmosphere', {'type': 'string', 'max_length': 255})
        assert isinstance(f, models.CharField)
        assert f.max_length == 255


# ---------------------------------------------------------------------------
# _make_simple_global_model — generated class structure
# ---------------------------------------------------------------------------

class TestMakeSimpleGlobalModel:
    """Verify the structure of classes generated by _make_simple_global_model."""

    @pytest.fixture
    def make(self, monkeypatch):
        """Return the factory, with _GLOBALS_MAP replaced by a minimal fixture."""
        import api.workflow as wf
        import api.models as m

        fake_map = {
            'widget': {
                'model': 'Widget',
                'public': False,
                'private': True,
                'fields': {
                    'name': {'type': 'string'},
                    'color': {'type': 'string'},
                    'weight': {'type': 'number'},
                },
            },
            'gadget': {
                'model': 'Gadget',
                'public': True,
                'private': True,
                'fields': {
                    'name': {'type': 'string'},
                    'serial': {'type': 'string'},
                },
            },
            'gizmo': {
                'model': 'Gizmo',
                'public': True,
                'private': False,
                'fields': {
                    'name': {'type': 'string'},
                },
            },
        }
        monkeypatch.setattr(wf, '_GLOBALS_MAP', fake_map)
        return m._make_simple_global_model

    def test_class_name_matches_model_key(self, make):
        Widget = make('widget')
        assert Widget.__name__ == 'Widget'

    def test_module_is_api_models(self, make):
        Widget = make('widget')
        assert Widget.__module__ == 'api.models'

    def test_inherits_from_global_model(self, make):
        from api.models import GlobalModel
        Widget = make('widget')
        assert issubclass(Widget, GlobalModel)

    def test_private_only_user_fk_is_not_nullable(self, make):
        Widget = make('widget')
        user_field = Widget._meta.get_field('user')
        assert not user_field.null

    def test_public_private_user_fk_is_nullable(self, make):
        Gadget = make('gadget')
        user_field = Gadget._meta.get_field('user')
        assert user_field.null

    def test_public_only_user_fk_is_nullable(self, make):
        Gizmo = make('gizmo')
        user_field = Gizmo._meta.get_field('user')
        assert user_field.null

    def test_inline_fields_are_present(self, make):
        Widget = make('widget')
        field_names = {f.name for f in Widget._meta.get_fields()}
        assert 'name' in field_names
        assert 'color' in field_names
        assert 'weight' in field_names

    def test_ref_fields_are_skipped(self, monkeypatch):
        """$ref fields in a global's fields section are additional_fields references
        and must not become model columns."""
        import api.workflow as wf
        import api.models as m
        monkeypatch.setattr(wf, '_GLOBALS_MAP', {
            'thing': {
                'model': 'Thing',
                'public': False,
                'private': True,
                'fields': {
                    'name': {'type': 'string'},
                    'clay_body': {'$ref': '@clay_body.name'},
                },
            },
        })
        Thing = m._make_simple_global_model('thing')
        field_names = {f.name for f in Thing._meta.get_fields()}
        assert 'name' in field_names
        assert 'clay_body' not in field_names

    def test_related_name_pluralizes_global_name(self, make):
        Widget = make('widget')
        user_field = Widget._meta.get_field('user')
        assert user_field.remote_field.get_accessor_name() == 'widgets'

    def test_private_only_has_one_constraint(self, make):
        Widget = make('widget')
        assert len(Widget._meta.constraints) == 1
        c = Widget._meta.constraints[0]
        assert c.name == 'uniq_widget_name_per_user'
        assert list(c.fields) == ['user', 'name']
        assert c.condition is None

    def test_public_private_has_two_constraints(self, make):
        Gadget = make('gadget')
        names = {c.name for c in Gadget._meta.constraints}
        assert names == {'uniq_gadget_name_per_user', 'uniq_gadget_name_public'}

    def test_public_only_has_one_public_constraint(self, make):
        Gizmo = make('gizmo')
        assert len(Gizmo._meta.constraints) == 1
        assert Gizmo._meta.constraints[0].name == 'uniq_gizmo_name_public'

    def test_str_returns_name(self, make):
        Widget = make('widget')
        instance = Widget.__new__(Widget)
        instance.name = 'My Widget'
        assert str(instance) == 'My Widget'

    def test_related_name_uses_plural_key_when_present(self, monkeypatch):
        """When the global config carries a 'plural' key the factory must use it
        for the user FK related_name instead of auto-pluralizing the global name."""
        import api.workflow as wf
        import api.models as m
        monkeypatch.setattr(wf, '_GLOBALS_MAP', {
            'entity': {
                'model': 'Entity',
                'plural': 'entities',
                'public': False,
                'private': True,
                'fields': {'name': {'type': 'string'}},
            },
        })
        Entity = m._make_simple_global_model('entity')
        user_field = Entity._meta.get_field('user')
        assert user_field.remote_field.get_accessor_name() == 'entities'

    def test_unknown_global_raises(self, make):
        with pytest.raises(ValueError, match='Unknown global'):
            make('nonexistent')


# ---------------------------------------------------------------------------
# _make_compose_global_models — generated class structure
# ---------------------------------------------------------------------------

class TestMakeComposeGlobalModels:
    """Verify the structure of classes generated by _make_compose_global_models."""

    @pytest.fixture
    def make(self, monkeypatch):
        import api.workflow as wf
        import api.models as m

        fake_map = {
            'component': {
                'model': 'Component',
                'public': True,
                'private': True,
                'fields': {'name': {'type': 'string'}},
            },
            'method': {
                'model': 'Method',
                'public': False,
                'private': True,
                'fields': {'name': {'type': 'string'}},
            },
            'composite': {
                'model': 'Composite',
                'public': True,
                'private': True,
                'compose_from': {
                    'components': {
                        'global': 'component',
                        'ordered': True,
                        'through_fields': {
                            'method': {'$ref': '@method.name', 'required': False},
                        },
                    },
                },
                'fields': {
                    'name': {'type': 'string'},
                    'notes': {'type': 'string'},
                    'source': {'$ref': '@component.name'},
                },
            },
        }
        monkeypatch.setattr(wf, '_GLOBALS_MAP', fake_map)
        return m._make_compose_global_models

    def test_returns_two_model_classes(self, make):
        CompositeModel, LayerModel = make('composite')
        assert CompositeModel.__name__ == 'Composite'
        assert LayerModel.__name__ == 'CompositeLayer'

    def test_composite_inherits_global_model(self, make):
        from api.models import GlobalModel
        CompositeModel, _ = make('composite')
        assert issubclass(CompositeModel, GlobalModel)

    def test_layer_model_does_not_inherit_global_model(self, make):
        from api.models import GlobalModel
        _, LayerModel = make('composite')
        assert not issubclass(LayerModel, GlobalModel)

    def test_composite_has_stored_name_field(self, make):
        CompositeModel, _ = make('composite')
        name_field = CompositeModel._meta.get_field('name')
        assert isinstance(name_field, models.CharField)
        assert name_field.max_length == 2047

    def test_composite_has_m2m_via_through_table(self, make):
        CompositeModel, LayerModel = make('composite')
        m2m = CompositeModel._meta.get_field('components')
        assert isinstance(m2m, models.ManyToManyField)

    def test_composite_has_inline_fields_and_global_ref_fk(self, make):
        CompositeModel, _ = make('composite')
        field_names = {f.name for f in CompositeModel._meta.get_fields()}
        assert 'notes' in field_names
        # Global $ref fields become FK columns on the composite model (like
        # GlazeCombination.firing_temperature).
        source_field = CompositeModel._meta.get_field('source')
        assert isinstance(source_field, models.ForeignKey)

    def test_layer_has_order_field_when_ordered(self, make):
        _, LayerModel = make('composite')
        order_field = LayerModel._meta.get_field('order')
        assert isinstance(order_field, models.PositiveSmallIntegerField)

    def test_layer_has_through_field_as_fk(self, make):
        _, LayerModel = make('composite')
        method_field = LayerModel._meta.get_field('method')
        assert isinstance(method_field, models.ForeignKey)
        assert method_field.null  # required: false → nullable

    def test_layer_ordering_by_order(self, make):
        _, LayerModel = make('composite')
        assert list(LayerModel._meta.ordering) == ['order']

    def test_composite_compute_name_joins_with_separator(self, make):
        from api.models import COMPOSITE_NAME_SEPARATOR as SEP
        CompositeModel, _ = make('composite')
        assert CompositeModel.compute_name(['A', 'B', 'C']) == f'A{SEP}B{SEP}C'

    def test_composite_has_two_constraints_for_public_private(self, make):
        CompositeModel, _ = make('composite')
        names = {c.name for c in CompositeModel._meta.constraints}
        assert names == {'uniq_composite_name_public', 'uniq_composite_name_per_user'}

    def test_layer_save_is_present(self, make):
        """The factory must attach a save() method to the layer model."""
        _, LayerModel = make('composite')
        assert 'save' in LayerModel.__dict__

    def test_get_or_create_with_layers_accepts_compose_key_kwarg(self, make):
        """get_or_create_with_layers must accept the compose_key name as a keyword."""
        CompositeModel, _ = make('composite')
        # Verify the method exists; calling it requires DB access so we just
        # confirm it doesn't raise TypeError on the keyword check alone.
        import inspect
        assert hasattr(CompositeModel, 'get_or_create_with_layers')
        # The method should also accept the generic 'components' alias.
        sig = inspect.signature(CompositeModel.get_or_create_with_layers)
        assert 'kwargs' in str(sig)  # accepts **kwargs

    def test_no_compose_from_raises(self, monkeypatch):
        import api.workflow as wf
        import api.models as m
        monkeypatch.setattr(wf, '_GLOBALS_MAP', {
            'plain': {'model': 'Plain', 'public': False, 'private': True,
                      'fields': {'name': {'type': 'string'}}},
        })
        with pytest.raises(ValueError, match='no compose_from'):
            m._make_compose_global_models('plain')


# ---------------------------------------------------------------------------
# _make_favorite_model — generated class structure
# ---------------------------------------------------------------------------

class TestMakeFavoriteModel:
    """Verify the structure of classes generated by _make_favorite_model."""

    @pytest.fixture
    def make(self, monkeypatch):
        import api.workflow as wf
        import api.models as m

        fake_map = {
            'widget': {
                'model': 'Widget',
                'public': True,
                'private': True,
                'favoritable': True,
                'fields': {'name': {'type': 'string'}},
            },
        }
        monkeypatch.setattr(wf, '_GLOBALS_MAP', fake_map)
        return m._make_favorite_model

    def test_class_name_is_favorite_model_name(self, make):
        FavWidget = make('widget')
        assert FavWidget.__name__ == 'FavoriteWidget'

    def test_module_is_api_models(self, make):
        FavWidget = make('widget')
        assert FavWidget.__module__ == 'api.models'

    def test_inherits_from_favorite_model(self, make):
        from api.models import FavoriteModel
        FavWidget = make('widget')
        assert issubclass(FavWidget, FavoriteModel)

    def test_global_fk_field_is_global_name(self, make):
        FavWidget = make('widget')
        assert FavWidget.global_fk_field == 'widget'

    def test_user_related_name_uses_plural(self, make):
        FavWidget = make('widget')
        user_field = FavWidget._meta.get_field('user')
        assert user_field.remote_field.get_accessor_name() == 'favorite_widgets'

    def test_global_fk_has_favorited_by_related_name(self, make):
        FavWidget = make('widget')
        fk = FavWidget._meta.get_field('widget')
        assert fk.remote_field.get_accessor_name() == 'favorited_by'

    def test_constraint_name(self, make):
        FavWidget = make('widget')
        constraint_names = {c.name for c in FavWidget._meta.constraints}
        assert 'uniq_favorite_widget_per_user' in constraint_names

    def test_get_favorite_ids_for_is_inherited(self, make):
        FavWidget = make('widget')
        assert hasattr(FavWidget, 'get_favorite_ids_for')
        # Method is inherited — it should not be defined directly on the subclass.
        assert 'get_favorite_ids_for' not in FavWidget.__dict__

    def test_unknown_global_raises(self, make):
        with pytest.raises(ValueError, match='Unknown global'):
            make('nonexistent')

    def test_plural_key_used_in_user_related_name(self, monkeypatch):
        """explicit plural key overrides auto-pluralize for related_name."""
        import api.workflow as wf
        import api.models as m
        monkeypatch.setattr(wf, '_GLOBALS_MAP', {
            'entity': {
                'model': 'Entity',
                'plural': 'entities',
                'public': True,
                'private': True,
                'favoritable': True,
                'fields': {'name': {'type': 'string'}},
            },
        })
        FavEntity = m._make_favorite_model('entity')
        user_field = FavEntity._meta.get_field('user')
        assert user_field.remote_field.get_accessor_name() == 'favorite_entities'


# ---------------------------------------------------------------------------
# Converted existing globals — schema sanity checks
# ---------------------------------------------------------------------------

class TestConvertedSimpleGlobals:
    """Smoke-test the three existing globals that were converted to factory output.

    Migration compatibility is verified by `manage.py makemigrations --check`
    in CI; these tests guard the Python-level structure.
    """

    @pytest.mark.parametrize('model_name,global_name', [
        ('Location', 'location'),
        ('ClayBody', 'clay_body'),
        ('GlazeMethod', 'glaze_method'),
    ])
    def test_model_registered_in_workflow_globals(self, model_name, global_name):
        from api.workflow import get_global_config
        config = get_global_config(global_name)
        assert config['model'] == model_name

    @pytest.mark.parametrize('cls_name', ['Location', 'ClayBody', 'GlazeMethod'])
    def test_model_in_global_registry(self, cls_name):
        from api.models import GlobalModel
        names = {c.__name__ for c in GlobalModel._registry}
        assert cls_name in names

    def test_location_user_fk_is_not_nullable(self):
        from api.models import Location
        assert not Location._meta.get_field('user').null

    def test_clay_body_user_fk_is_nullable(self):
        from api.models import ClayBody
        assert ClayBody._meta.get_field('user').null

    def test_glaze_method_has_short_description(self):
        from api.models import GlazeMethod
        field = GlazeMethod._meta.get_field('short_description')
        assert isinstance(field, models.CharField)
        assert field.max_length == 1024
