import pytest
from django.apps import apps
from django.contrib.auth.models import User
from rest_framework.request import Request
from rest_framework.test import APIClient, APIRequestFactory

from api.models import ClayBody, FiringTemperature, GlazeCombination, GlazeType, Tag
from api.serializer_registry import _GLOBAL_ENTRY_SERIALIZERS
from api.views import _apply_global_filters, _global_entries_impl


def _get_serializer(model_name: str):
    model_cls = apps.get_model('api', model_name)
    return _GLOBAL_ENTRY_SERIALIZERS[model_cls]


@pytest.mark.django_db
class TestAutoGeneratedTagSerializer:
    def test_serializes_private_tag(self):
        TagSerializer = _get_serializer('Tag')
        user = User.objects.create(username='taguser@example.com', email='taguser@example.com')
        tag = Tag.objects.create(user=user, name='personal')
        data = TagSerializer(tag).data
        assert data['name'] == 'personal'
        assert data['is_public'] is False
        assert isinstance(data['id'], str)

    def test_color_field_present(self):
        TagSerializer = _get_serializer('Tag')
        user = User.objects.create(username='coloruser@example.com', email='coloruser@example.com')
        tag = Tag.objects.create(user=user, name='teal', color='#008080')
        data = TagSerializer(tag).data
        assert data['color'] == '#008080'

    def test_globals_endpoint_returns_tags_with_correct_shape(self):
        user = User.objects.create(username='tagapi@example.com', email='tagapi@example.com')
        Tag.objects.create(user=user, name='ocean', color='#0000ff')
        c = APIClient()
        c.force_authenticate(user=user)
        resp = c.get('/api/globals/tag/')
        assert resp.status_code == 200
        items = resp.json()
        assert len(items) == 1
        assert items[0]['name'] == 'ocean'
        assert items[0]['color'] == '#0000ff'
        assert items[0]['is_public'] is False
        assert isinstance(items[0]['id'], str)


@pytest.mark.django_db
class TestAutoGeneratedClayBodySerializer:
    def test_short_description_included(self):
        ClayBodySerializer = _get_serializer('ClayBody')
        user = User.objects.create(username='cbuser@example.com', email='cbuser@example.com')
        cb = ClayBody.objects.create(user=user, name='Stoneware', short_description='High-fire gray')
        data = ClayBodySerializer(cb).data
        assert data['name'] == 'Stoneware'
        assert data['short_description'] == 'High-fire gray'
        assert data['is_public'] is False
        assert isinstance(data['id'], str)

    def test_globals_endpoint_includes_short_description(self):
        user = User.objects.create(username='cbapi@example.com', email='cbapi@example.com')
        ClayBody.objects.create(user=user, name='Porcelain', short_description='Translucent')
        c = APIClient()
        c.force_authenticate(user=user)
        resp = c.get('/api/globals/clay_body/')
        assert resp.status_code == 200
        items = resp.json()
        assert len(items) == 1
        assert items[0]['short_description'] == 'Translucent'


@pytest.mark.django_db
class TestAutoGeneratedGlazeTypeSerializer:
    def test_extra_fields_included(self):
        GlazeTypeSerializer = _get_serializer('GlazeType')
        gt = GlazeType.objects.create(
            user=None, name='Celadon', short_description='Pale green', test_tile_image=''
        )
        data = GlazeTypeSerializer(gt).data
        assert data['name'] == 'Celadon'
        assert data['short_description'] == 'Pale green'
        assert data['is_public'] is True
        assert isinstance(data['id'], str)

    def test_globals_endpoint_includes_extra_fields(self):
        GlazeType.objects.create(user=None, name='Tenmoku', short_description='Iron black')
        user = User.objects.create(username='gtapi@example.com', email='gtapi@example.com')
        c = APIClient()
        c.force_authenticate(user=user)
        resp = c.get('/api/globals/glaze_type/')
        assert resp.status_code == 200
        items = resp.json()
        assert len(items) == 1
        assert items[0]['short_description'] == 'Iron black'


@pytest.mark.django_db
class TestGlobalEntries:
    def test_piece_global_uses_registered_rich_serializer_without_glaze_hack(
        self, client, piece
    ):
        response = client.get('/api/globals/piece/')

        assert response.status_code == 200
        assert response.json() == [
            {
                'id': str(piece.id),
                'name': 'Test Bowl',
                'created': piece.created.isoformat().replace('+00:00', 'Z'),
                'last_modified': piece.last_modified.isoformat().replace(
                    '+00:00', 'Z'
                ),
                'thumbnail': None,
                'shared': False,
                'can_edit': True,
                'current_state': {'state': 'designed'},
                'current_location': None,
                'tags': [],
            }
        ]

    def test_all_factory_globals_have_registered_serializer(self):
        from api.workflow import get_global_config, get_global_names, is_factory_global
        for global_name in get_global_names():
            if not is_factory_global(global_name):
                continue
            model_name = get_global_config(global_name)['model']
            model_cls = apps.get_model('api', model_name)
            assert model_cls in _GLOBAL_ENTRY_SERIALIZERS, (
                f'{global_name} ({model_name}) has no registered entry serializer'
            )

    def test_default_get_serializer_used_when_no_rich_serializer_registered(self, client, monkeypatch):
        monkeypatch.delitem(_GLOBAL_ENTRY_SERIALIZERS, apps.get_model('api', 'Location'), raising=False)

        response = client.get('/api/globals/location/')

        assert response.status_code == 200
        assert response.json() == []

    def test_default_post_response_used_when_no_rich_serializer_registered(self, client, monkeypatch):
        location_model = apps.get_model('api', 'Location')
        monkeypatch.delitem(_GLOBAL_ENTRY_SERIALIZERS, location_model, raising=False)

        response = client.post(
            '/api/globals/location/',
            {'values': {'name': 'Default Serializer Shelf'}},
            format='json',
        )

        assert response.status_code == 201
        assert response.json() == {
            'id': response.json()['id'],
            'name': 'Default Serializer Shelf',
        }

    def test_post_rejects_unknown_values_field(self, client):
        response = client.post(
            '/api/globals/location/',
            {'values': {'name': 'Shelf', 'unknown': 'nope'}},
            format='json',
        )

        assert response.status_code == 400
        assert response.json() == {'detail': 'Invalid field: unknown'}

    def test_default_get_serializer_stringifies_relation_display_field(self, user, monkeypatch):
        temp = FiringTemperature.objects.create(
            user=None, name='Cone 6 Electric', cone='6', temperature_c=1222, atmosphere='oxidation'
        )
        combo = GlazeCombination.objects.create(
            user=user,
            name='Relation Display',
            firing_temperature=temp,
        )
        monkeypatch.delitem(_GLOBAL_ENTRY_SERIALIZERS, GlazeCombination, raising=False)
        monkeypatch.setattr(
            'api.views.get_global_model_and_field',
            lambda global_name: (
                GlazeCombination,
                {'firing_temperature': {'$ref': '@firing_temperature.name'}},
                'firing_temperature',
            ),
        )
        monkeypatch.setattr('api.views.is_public_global', lambda global_name: False)
        monkeypatch.setattr('api.views.is_private_global', lambda global_name: True)
        django_request = APIRequestFactory().get('/api/globals/fake/')
        request = Request(django_request)
        request._user = user

        response = _global_entries_impl(request, 'fake')

        assert response.data == [
            {
                'id': str(combo.pk),
                'name': 'Cone 6 Electric',
                'is_public': False,
            }
        ]


class TestApplyGlobalFilters:
    class RecordingQuerySet:
        def __init__(self):
            self.filters = []

        def filter(self, **kwargs):
            self.filters.append(kwargs)
            return self

    class FilterableModel:
        filterable_fields = {
            'is_food_safe': {'type': 'boolean'},
            'runs': {'type': 'boolean'},
            'layers__glaze_type_id': {'type': 'm2m_id', 'param': 'glaze_type_ids'},
            'firing_temperature_id': {'type': 'fk_id'},
        }

    def test_applies_boolean_m2m_and_fk_filters(self):
        qs = self.RecordingQuerySet()
        django_request = APIRequestFactory().get(
            '/api/globals/glaze_combination/',
            {
                'is_food_safe': 'false',
                'runs': 'true',
                'glaze_type_ids': '1, 2',
                'firing_temperature_id': '9',
            },
        )
        request = Request(django_request)

        result = _apply_global_filters(qs, self.FilterableModel, request)

        assert result is qs
        assert qs.filters == [
            {'is_food_safe': False},
            {'runs': True},
            {'layers__glaze_type_id': '1'},
            {'layers__glaze_type_id': '2'},
            {'firing_temperature_id': '9'},
        ]
