coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch:
      default:
        target: auto
        threshold: 2%

comment:
  layout: "reach,diff,flags,files"
  behavior: default

flags:
  code:
    paths:
      - api/
      - web/src/
    carryforward: true
