[mypy]
python_version = 3.12
plugins =
    mypy_django_plugin.main,
    mypy_drf_plugin.main

disallow_untyped_defs = True
ignore_missing_imports = True
warn_unused_ignores = True
warn_redundant_casts = True

# Exclude migrations and test directories from strict checks
exclude = (?x)(
    ^api/migrations/
    | ^tests/
    | ^api/tests/
)

[mypy.plugins.django-stubs]
django_settings_module = backend.settings
