[pytest]
DJANGO_SETTINGS_MODULE = backend.test_settings
python_files = tests.py test_*.py *_tests.py
# Unset the environment variable pulled from .env files to ensure tests 
# run with the expected environment variables, which are set in the test functions themselves.
env = 
    U:CLOUDINARY_CLOUD_NAME
    U:CLOUDINARY_API_KEY
    U:CLOUDINARY_UPLOAD_FOLDER
    U:CLOUDINARY_UPLOAD_PRESET
