[tool.pytest]
DJANGO_SETTINGS_MODULE = backend.test_settings
python_files = tests.py test_*.py *_tests.py
# Unset the environment variable pulled from .env files to ensure tests 
# run with the expected environment variables, which are set in the test functions themselves.
env = 
    U:R2_ACCOUNT_ID
    U:R2_ACCESS_KEY_ID
    U:R2_SECRET_ACCESS_KEY
    U:R2_BUCKET_NAME
    U:R2_PUBLIC_URL
