# Generated by Django 6.0.3 on 2026-04-30 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClayBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clay_bodies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FiringTemperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("04", "04"),
                            ("03", "03"),
                            ("02", "02"),
                            ("01", "01"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("temperature_c", models.IntegerField(blank=True, null=True)),
                (
                    "atmosphere",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firing_temperatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlazeCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=2047)),
                (
                    "test_tile_image",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("is_food_safe", models.BooleanField(blank=True, null=True)),
                ("runs", models.BooleanField(blank=True, null=True)),
                ("highlights_grooves", models.BooleanField(blank=True, null=True)),
                (
                    "is_different_on_white_and_brown_clay",
                    models.BooleanField(blank=True, null=True),
                ),
                ("apply_thin", models.BooleanField(blank=True, null=True)),
                (
                    "firing_temperature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glaze_combinations",
                        to="api.firingtemperature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_combinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteGlazeCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_glaze_combinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "glaze_combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="api.glazecombination",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlazeMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlazeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "test_tile_image",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("is_food_safe", models.BooleanField(blank=True, null=True)),
                ("runs", models.BooleanField(blank=True, null=True)),
                ("highlights_grooves", models.BooleanField(blank=True, null=True)),
                (
                    "is_different_on_white_and_brown_clay",
                    models.BooleanField(blank=True, null=True),
                ),
                ("apply_thin", models.BooleanField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GlazeCombinationLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="api.glazecombination",
                    ),
                ),
                (
                    "glaze_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glaze_combination_layers",
                        to="api.glazemethod",
                    ),
                ),
                (
                    "glaze_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="api.glazetype"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="glazecombination",
            name="glaze_types",
            field=models.ManyToManyField(
                related_name="combinations",
                through="api.GlazeCombinationLayer",
                to="api.glazetype",
            ),
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("fields_last_modified", models.DateTimeField(auto_now=True)),
                ("thumbnail", models.JSONField(blank=True, default=None, null=True)),
                ("workflow_version", models.CharField(default="0.0.3", max_length=32)),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces",
                        to="api.location",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fields_last_modified"],
            },
        ),
        migrations.CreateModel(
            name="PieceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=64)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("images", models.JSONField(default=list)),
                ("additional_fields", models.JSONField(default=dict)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="api.piece",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created"],
            },
        ),
        migrations.CreateModel(
            name="PieceStateClayBodyRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "clay_body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="piece_state_refs",
                        to="api.claybody",
                    ),
                ),
                (
                    "piece_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clay_bodies_refs",
                        to="api.piecestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PieceStateGlazeCombinationRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "glaze_combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="piece_state_refs",
                        to="api.glazecombination",
                    ),
                ),
                (
                    "piece_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_combinations_refs",
                        to="api.piecestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PieceStateLocationRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="piece_state_refs",
                        to="api.location",
                    ),
                ),
                (
                    "piece_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations_refs",
                        to="api.piecestate",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PieceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="api.piece",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="piece_links",
                        to="api.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid_subject",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("profile_image_url", models.URLField(blank=True, default="")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="claybody",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="uniq_clay_body_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="claybody",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_clay_body_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="firingtemperature",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_firing_temperature_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteglazecombination",
            constraint=models.UniqueConstraint(
                fields=("user", "glaze_combination"),
                name="uniq_favorite_glaze_combination_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazemethod",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_glaze_method_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="glazetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="uniq_glaze_type_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_glaze_type_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazecombination",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_glaze_combination_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazecombination",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="uniq_glaze_combination_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_location_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestateclaybodyref",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "field_name"),
                name="uniq_piece_state_clay_body_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestateglazecombinationref",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "field_name"),
                name="uniq_piece_state_glaze_combination_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestatelocationref",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "field_name"),
                name="uniq_piece_state_location_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_tag_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="piecetag",
            constraint=models.UniqueConstraint(
                fields=("piece", "tag"), name="uniq_piece_tag"
            ),
        ),
    ]
