# Generated by Django 6.0.4 on 2026-05-28 03:12

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicLibraryVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fixture_hash", models.CharField(max_length=64)),
                ("imported_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "public library version",
                "verbose_name_plural": "public library version",
            },
        ),
        migrations.CreateModel(
            name="AsyncTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("success", "Success"),
                            ("failure", "Failure"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("task_type", models.CharField(max_length=255)),
                ("input_params", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, null=True)),
                ("error", models.TextField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="async_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="ClayBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clay_bodies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clay Body",
                "verbose_name_plural": "Clay Bodies",
            },
        ),
        migrations.CreateModel(
            name="FiringTemperature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "cone",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("04", "04"),
                            ("03", "03"),
                            ("02", "02"),
                            ("01", "01"),
                            ("1", "1"),
                            ("2", "2"),
                            ("3", "3"),
                            ("4", "4"),
                            ("5", "5"),
                            ("6", "6"),
                            ("7", "7"),
                            ("8", "8"),
                            ("9", "9"),
                            ("10", "10"),
                        ],
                        default="",
                        max_length=16,
                    ),
                ),
                ("temperature_c", models.IntegerField(blank=True, null=True)),
                (
                    "atmosphere",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="firing_temperatures",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Firing Temperature",
                "verbose_name_plural": "Firing Temperatures",
            },
        ),
        migrations.CreateModel(
            name="GlazeCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=2047)),
                ("is_food_safe", models.BooleanField(blank=True, null=True)),
                ("runs", models.BooleanField(blank=True, null=True)),
                ("highlights_grooves", models.BooleanField(blank=True, null=True)),
                (
                    "is_different_on_white_and_brown_clay",
                    models.BooleanField(blank=True, null=True),
                ),
                ("apply_thin", models.BooleanField(blank=True, null=True)),
                (
                    "firing_temperature",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glaze_combinations",
                        to="api.firingtemperature",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_combinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Glaze Combination",
                "verbose_name_plural": "Glaze Combinations",
            },
        ),
        migrations.CreateModel(
            name="FavoriteGlazeCombination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorite_glaze_combinations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "glaze_combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorited_by",
                        to="api.glazecombination",
                    ),
                ),
            ],
            options={
                "verbose_name": "Favorite Glaze Combination",
                "verbose_name_plural": "Favorite Glaze Combinations",
            },
        ),
        migrations.CreateModel(
            name="GlazeMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Glaze Method",
                "verbose_name_plural": "Glaze Methods",
            },
        ),
        migrations.CreateModel(
            name="GlazeType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "short_description",
                    models.CharField(blank=True, default="", max_length=1024),
                ),
                ("is_food_safe", models.BooleanField(blank=True, null=True)),
                ("runs", models.BooleanField(blank=True, null=True)),
                ("highlights_grooves", models.BooleanField(blank=True, null=True)),
                (
                    "is_different_on_white_and_brown_clay",
                    models.BooleanField(blank=True, null=True),
                ),
                ("apply_thin", models.BooleanField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_types",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Glaze Type",
                "verbose_name_plural": "Glaze Types",
            },
        ),
        migrations.CreateModel(
            name="GlazeCombinationLayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="layers",
                        to="api.glazecombination",
                    ),
                ),
                (
                    "glaze_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="glaze_combination_layers",
                        to="api.glazemethod",
                    ),
                ),
                (
                    "glaze_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.glazetype"
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="glazecombination",
            name="glaze_types",
            field=models.ManyToManyField(
                related_name="combinations",
                through="api.GlazeCombinationLayer",
                to="api.glazetype",
            ),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.CharField(max_length=2048)),
                (
                    "cloudinary_public_id",
                    models.CharField(blank=True, max_length=1024, null=True),
                ),
                ("cloud_name", models.CharField(blank=True, max_length=255, null=True)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="glazetype",
            name="test_tile_image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.image",
            ),
        ),
        migrations.AddField(
            model_name="glazecombination",
            name="test_tile_image",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="api.image",
            ),
        ),
        migrations.CreateModel(
            name="InviteCode",
            fields=[
                (
                    "code",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(blank=True, null=True)),
                (
                    "used_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="redeemed_invite_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Location",
                "verbose_name_plural": "Locations",
            },
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("fields_last_modified", models.DateTimeField(auto_now=True)),
                ("shared", models.BooleanField(default=False)),
                ("showcase_story", models.TextField(blank=True, default="")),
                ("showcase_fields", models.JSONField(default=list)),
                ("workflow_version", models.CharField(default="0.0.3", max_length=32)),
                ("is_editable", models.BooleanField(default=False)),
                (
                    "current_location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pieces",
                        to="api.location",
                    ),
                ),
                (
                    "thumbnail",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thumbnail_for_pieces",
                        to="api.image",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-fields_last_modified"],
            },
        ),
        migrations.CreateModel(
            name="PieceState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("state", models.CharField(max_length=64)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("order", models.PositiveIntegerField(blank=True, null=True)),
                ("has_been_edited", models.BooleanField(default=False)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="api.piece",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created"],
            },
        ),
        migrations.CreateModel(
            name="PieceStateClayBodyRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "clay_body",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_state_refs",
                        to="api.claybody",
                    ),
                ),
                (
                    "piece_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clay_bodies_refs",
                        to="api.piecestate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piece State Clay Body Ref",
                "verbose_name_plural": "Piece State Clay Body Refs",
            },
        ),
        migrations.CreateModel(
            name="PieceStateGlazeCombinationRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "glaze_combination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_state_refs",
                        to="api.glazecombination",
                    ),
                ),
                (
                    "piece_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="glaze_combinations_refs",
                        to="api.piecestate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piece State Glaze Combination Ref",
                "verbose_name_plural": "Piece State Glaze Combination Refs",
            },
        ),
        migrations.CreateModel(
            name="PieceStateImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("caption", models.CharField(blank=True, default="", max_length=1024)),
                ("crop", models.JSONField(blank=True, default=None, null=True)),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="piece_state_links",
                        to="api.image",
                    ),
                ),
                (
                    "piece_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_links",
                        to="api.piecestate",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="CropRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("source", models.JSONField()),
                ("crop", models.JSONField(blank=True, null=True)),
                ("mask_asset", models.JSONField(blank=True, null=True)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("no_subject", "No Subject"),
                            ("error", "Error"),
                        ],
                        max_length=32,
                    ),
                ),
                ("error", models.TextField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "async_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="crop_runs",
                        to="api.asynctask",
                    ),
                ),
                (
                    "submitter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_crop_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crop_runs",
                        to="api.image",
                    ),
                ),
                (
                    "piece_state_image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="crop_runs",
                        to="api.piecestateimage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="PieceStateLocationRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("field_name", models.CharField(max_length=100)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_state_refs",
                        to="api.location",
                    ),
                ),
                (
                    "piece_state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations_refs",
                        to="api.piecestate",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piece State Location Ref",
                "verbose_name_plural": "Piece State Location Refs",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("color", models.CharField(blank=True, default="", max_length=7)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
            },
        ),
        migrations.CreateModel(
            name="PieceTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField()),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tag_links",
                        to="api.piece",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="piece_links",
                        to="api.tag",
                    ),
                ),
            ],
            options={
                "verbose_name": "Piece Tag",
                "verbose_name_plural": "Piece Tags",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "openid_subject",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("alias", models.CharField(blank=True, default="", max_length=50)),
                ("preferences", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="claybody",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="uniq_clay_body_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="claybody",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_clay_body_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="firingtemperature",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_firing_temperature_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="favoriteglazecombination",
            constraint=models.UniqueConstraint(
                fields=("user", "glaze_combination"),
                name="uniq_favorite_glaze_combination_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazemethod",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_glaze_method_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("cloud_name__isnull", False),
                    ("cloudinary_public_id__isnull", False),
                ),
                fields=("cloud_name", "cloudinary_public_id"),
                name="uniq_image_cloudinary_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="image",
            constraint=models.UniqueConstraint(
                condition=models.Q(("cloudinary_public_id__isnull", True)),
                fields=("url",),
                name="uniq_image_url_without_cloudinary_id",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="uniq_glaze_type_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazetype",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_glaze_type_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazecombination",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", True)),
                fields=("name",),
                name="uniq_glaze_combination_name_public",
            ),
        ),
        migrations.AddConstraint(
            model_name="glazecombination",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "name"),
                name="uniq_glaze_combination_name_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_location_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestateclaybodyref",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "field_name"),
                name="uniq_piece_state_clay_body_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestateglazecombinationref",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "field_name"),
                name="uniq_piece_state_glaze_combination_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestateimage",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "order"), name="uniq_piece_state_image_order"
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestateimage",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "image"), name="uniq_piece_state_image"
            ),
        ),
        migrations.AddIndex(
            model_name="croprun",
            index=models.Index(
                fields=["piece_state_image", "-created"],
                name="api_croprun_piece_s_5474cc_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="piecestatelocationref",
            constraint=models.UniqueConstraint(
                fields=("piece_state", "field_name"),
                name="uniq_piece_state_location_ref",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="uniq_tag_name_per_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="piecetag",
            constraint=models.UniqueConstraint(
                fields=("piece", "tag"), name="uniq_piece_tag"
            ),
        ),
    ]
