# Generated by Django 6.0.3 on 2026-04-04 18:41

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('fields_last_modified', models.DateTimeField(auto_now=True)),
                ('thumbnail', models.CharField(blank=True, default='', max_length=1024)),
            ],
            options={
                'ordering': ['-fields_last_modified'],
            },
        ),
        migrations.CreateModel(
            name='PieceState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('images', models.JSONField(default=list)),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='api.piece')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
