# Generated by Django 6.0.4 on 2026-06-02 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="invitecode",
            name="used_at",
        ),
        migrations.RemoveField(
            model_name="invitecode",
            name="used_by",
        ),
        migrations.AddField(
            model_name="invitecode",
            name="sent",
            field=models.BooleanField(default=False),
        ),
    ]
