# Generated by Django 6.0.4 on 2026-06-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_remove_invitecode_used_at_remove_invitecode_used_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctask",
            name="progress",
            field=models.IntegerField(default=0),
        ),
    ]
