# Generated by Django 6.0.3 on 2026-04-05 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='piece',
            name='workflow_version',
            field=models.CharField(default='0.0.2', max_length=32),
        ),
        migrations.AddField(
            model_name='piecestate',
            name='additional_fields',
            field=models.JSONField(default=dict),
        ),
    ]
