# Generated by Django 6.0.4 on 2026-06-08 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_piecestate_piece_lm_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="supportthread",
            name="user",
        ),
        migrations.AlterField(
            model_name="croprun",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="crop_runs",
                to="api.image",
            ),
        ),
        migrations.AlterField(
            model_name="croprun",
            name="piece_state_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="crop_runs",
                to="api.piecestateimage",
            ),
        ),
        migrations.AlterField(
            model_name="piecestateimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="piece_state_links",
                to="api.image",
            ),
        ),
        migrations.DeleteModel(
            name="SupportMessage",
        ),
        migrations.DeleteModel(
            name="SupportThread",
        ),
    ]
