# Generated by Django 6.0.4 on 2026-05-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_asynctask"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="showcase_fields",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="piece",
            name="showcase_story",
            field=models.TextField(blank=True, default=""),
        ),
    ]
