# Generated by Django 6.0.3 on 2026-04-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_scoping'),
    ]

    operations = [
        migrations.AddField(
            model_name='glazetype',
            name='apply_thin',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glazetype',
            name='highlights_grooves',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glazetype',
            name='is_different_on_white_and_brown_clay',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glazetype',
            name='is_food_safe',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glazetype',
            name='runs',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='glazetype',
            name='test_tile_image',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
