# Generated by Django 6.0.3 on 2026-04-12 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_glaze_type_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='claybody',
            name='uniq_clay_body_name_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='glazetype',
            name='uniq_glaze_type_name_per_user',
        ),
        migrations.AlterField(
            model_name='claybody',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clay_bodies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='glazetype',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glaze_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='claybody',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='uniq_clay_body_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='claybody',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('name',), name='uniq_clay_body_name_public'),
        ),
        migrations.AddConstraint(
            model_name='glazetype',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'name'), name='uniq_glaze_type_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='glazetype',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('name',), name='uniq_glaze_type_name_public'),
        ),
    ]
