# Generated by Django 6.0.3 on 2026-04-13 04:16

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_public_global_libraries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GlazeCombination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_tile_image', models.CharField(blank=True, default='', max_length=1024)),
                ('is_food_safe', models.BooleanField(blank=True, null=True)),
                ('runs', models.BooleanField(blank=True, null=True)),
                ('highlights_grooves', models.BooleanField(blank=True, null=True)),
                ('is_different_on_white_and_brown_clay', models.BooleanField(blank=True, null=True)),
                ('first_layer_glaze_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='first_layer_combinations', to='api.glazetype')),
                ('second_layer_glaze_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='second_layer_combinations', to='api.glazetype')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='glaze_combinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('first_layer_glaze_type', 'second_layer_glaze_type'), name='uniq_glaze_combination_public'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('user', 'first_layer_glaze_type', 'second_layer_glaze_type'), name='uniq_glaze_combination_per_user')],
            },
            bases=(api.models.ImmutableUserMixin, models.Model),
        ),
    ]
