# Generated by Django 6.0.4 on 2026-05-13 14:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_backfill_piece_state_order"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piecestate",
            options={"ordering": ["order", "created"]},
        ),
        migrations.AlterField(
            model_name="piecestate",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
