# Generated by Django 6.0.3 on 2026-04-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_glaze_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='glazecombination',
            name='name',
            field=models.CharField(blank=True, default='', editable=False, max_length=511),
        ),
    ]
