# Generated by Django 6.0.4 on 2026-06-13 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_agenttoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="agenttoken",
            name="token_hash",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
