# Generated by Django 6.0.3 on 2026-04-16 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_glaze_combination_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='glazecombination',
            name='glaze_types',
            field=models.ManyToManyField(related_name='combinations', through='api.GlazeCombinationLayer', to='api.glazetype'),
        ),
    ]
