# Generated by Django 6.0.3 on 2026-04-17 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_glazecombination_glaze_types'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='glazecombinationlayer',
            name='uniq_combination_layer_order',
        ),
    ]
