# Generated by Django 6.0.4 on 2026-05-19 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_croprun_piece_state_image"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="croprun",
            name="api_croprun_image_i_idx",
        ),
        migrations.RenameIndex(
            model_name="croprun",
            new_name="api_croprun_piece_s_5474cc_idx",
            old_name="api_croprun_psi_created_idx",
        ),
        migrations.AddField(
            model_name="image",
            name="height",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="width",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="piecestate",
            name="custom_fields",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
