# Generated by Django 6.0.3 on 2026-04-18 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_favorite_glaze_combination'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='glazecombinationlayer',
            name='glaze_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combination_layers', to='api.glazemethod'),
        ),
        migrations.CreateModel(
            name='FiringTemperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cone', models.CharField(blank=True, choices=[('04', '04'), ('03', '03'), ('02', '02'), ('01', '01'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='', max_length=16)),
                ('temperature_c', models.IntegerField(blank=True, null=True)),
                ('atmosphere', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firing_temperatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='glazecombination',
            name='firing_temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combinations', to='api.firingtemperature'),
        ),
        migrations.AddConstraint(
            model_name='firingtemperature',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('name',), name='uniq_firing_temperature_name_public'),
        ),
    ]
