# Generated by Django 6.0.3 on 2026-04-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_add_firing_temperature_and_through_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='glazecombination',
            name='apply_thin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
