# Generated by Django 6.0.3 on 2026-04-18 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_piece_thumbnail_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piece',
            name='thumbnail',
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
