# Generated by Django 6.0.3 on 2026-04-19 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_piece_thumbnail_jsonfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='glazecombination',
            name='firing_temperature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glaze_combinations', to='api.firingtemperature'),
        ),
        migrations.AlterField(
            model_name='glazecombinationlayer',
            name='glaze_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='glaze_combination_layers', to='api.glazemethod'),
        ),
        migrations.AlterField(
            model_name='glazecombinationlayer',
            name='glaze_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.glazetype'),
        ),
    ]
