# Generated by Django 6.0.3 on 2026-04-21 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_piecestateclaybodyref_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, default='', max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='api.piece')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piece_links', to='api.tag')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_tag_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='piecetag',
            constraint=models.UniqueConstraint(fields=('piece', 'tag'), name='uniq_piece_tag'),
        ),
    ]
