# Generated by Django 6.0.3 on 2026-04-21 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_piecestateclaybodyref_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(blank=True, choices=[('#E76F51', '#E76F51'), ('#F4A261', '#F4A261'), ('#E9C46A', '#E9C46A'), ('#7CB342', '#7CB342'), ('#2A9D8F', '#2A9D8F'), ('#4FC3F7', '#4FC3F7'), ('#5C6BC0', '#5C6BC0'), ('#7E57C2', '#7E57C2'), ('#EC407A', '#EC407A'), ('#D4A373', '#D4A373'), ('#90A4AE', '#90A4AE'), ('#EF5350', '#EF5350')], default='', max_length=16)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PieceTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField()),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_links', to='api.piece')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piece_links', to='api.tag')),
            ],
            options={
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='uniq_tag_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='piecetag',
            constraint=models.UniqueConstraint(fields=('piece', 'tag'), name='uniq_piece_tag'),
        ),
    ]
