# Generated by Django 6.0.3 on 2026-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_tag_piecetag_tag_uniq_tag_name_per_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="piece",
            name="workflow_version",
            field=models.CharField(default="0.0.3", max_length=32),
        ),
    ]
