# Generated by Django 6.0.4 on 2026-05-25 13:45

from django.db import migrations


def flatten_tutorials(apps, schema_editor):
    UserProfile = apps.get_model("api", "UserProfile")
    for profile in UserProfile.objects.all():
        if isinstance(profile.preferences, dict) and "tutorials" in profile.preferences:
            tutorials = profile.preferences.pop("tutorials")
            if isinstance(tutorials, dict):
                for key, value in tutorials.items():
                    # Move tutorial flags to the root of preferences JSON
                    if key not in profile.preferences:
                        profile.preferences[key] = value
            profile.save(update_fields=["preferences"])


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0027_backfill_tutorial_preferences"),
    ]

    operations = [
        migrations.RunPython(flatten_tutorials, migrations.RunPython.noop),
    ]
