/**
 * Generates TypeScript types from the OpenAPI schema.
 *
 * By default this reads the live schema from a backend running on port 8080.
 * Set GLAZE_SCHEMA_SOURCE to a local schema file path to avoid the network hop
 * in sandboxed environments.
 * Run via: npm run generate-types
 *
 * Transforms applied on top of the raw schema:
 *   - format: date-time  →  Date  (Axios delivers strings; api.ts converts at runtime)
 */

import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";
import { resolve } from "path";
import { pathToFileURL } from "url";
import { writeFileSync } from "fs";

// Bazel passes paths as positional args relative to execroot/_main.
// BAZEL_BINDIR is always set in Bazel actions; use it to anchor back to execroot.
// For local `npm run generate-types`, fall back to env vars / defaults.
const [,, argSchema, argOutput] = process.argv;
function resolvePath(p) {
  if (!p || p.startsWith("/")) return p;
  const bazelBindir = process.env.BAZEL_BINDIR;
  // BAZEL_BINDIR is e.g. "bazel-out/k8-fastbuild/bin" — 3 levels deep from execroot
  const execroot = bazelBindir
    ? resolve(process.cwd(), "../".repeat(bazelBindir.split("/").length))
    : process.cwd();
  return resolve(execroot, p);
}
const schemaSource = argSchema ?? process.env.GLAZE_SCHEMA_SOURCE;
const SCHEMA_SOURCE = schemaSource
  ? pathToFileURL(resolvePath(schemaSource))
  : new URL("http://localhost:8080/api/schema/?format=json");
const OUTPUT_PATH =
  resolvePath(argOutput) ?? process.env.GLAZE_OUTPUT_PATH ?? "src/util/generated-types.ts";

const HEADER = `\
/**
 * This file was auto-generated by openapi-typescript.
 * Run \`npm run generate-types\` to regenerate.
 * DO NOT EDIT BY HAND.
 */

`;

const DATE_NODE = ts.factory.createTypeReferenceNode(
  ts.factory.createIdentifier("Date"),
);

const ast = await openapiTS(SCHEMA_SOURCE, {
  transform(schemaObject) {
    if (schemaObject.format === "date-time") {
      return DATE_NODE;
    }
  },
});

writeFileSync(OUTPUT_PATH, HEADER + astToString(ast));
console.log(`✔ Generated ${OUTPUT_PATH}`);
