/**
 * Generates TypeScript types from the OpenAPI schema.
 *
 * By default this reads the live schema from a backend running on port 8080.
 * Set GLAZE_SCHEMA_SOURCE to a local schema file path to avoid the network hop
 * in sandboxed environments.
 * Run via: npm run generate-types
 *
 * Transforms applied on top of the raw schema:
 *   - format: date-time  →  Date  (Axios delivers strings; api.ts converts at runtime)
 */

import openapiTS, { astToString } from "openapi-typescript";
import ts from "typescript";
import { resolve } from "path";
import { fileURLToPath, pathToFileURL } from "url";
import { readFileSync, writeFileSync, lstatSync, unlinkSync } from "fs";

// Bazel passes paths as positional args relative to execroot/_main.
// BAZEL_BINDIR is always set in Bazel actions; use it to anchor back to execroot.
// For local `npm run generate-types`, fall back to env vars / defaults.
export function resolvePath(p) {
  if (!p || p.startsWith("/")) return p;
  const bazelBindir = process.env.BAZEL_BINDIR;
  // BAZEL_BINDIR is e.g. "bazel-out/k8-fastbuild/bin" — 3 levels deep from execroot
  const execroot = bazelBindir
    ? resolve(process.cwd(), "../".repeat(bazelBindir.split("/").length))
    : process.cwd();
  return resolve(execroot, p);
}

const HEADER = `\
/**
 * This file was auto-generated by openapi-typescript.
 * Run \`npm run generate-types\` to regenerate.
 * DO NOT EDIT BY HAND.
 */

`;

function isTypeIdentifier(name) {
  return /^[$A-Z_a-z][$\w]*$/.test(name);
}

export function renderSchemaAliasModule(openApiSchema) {
  const schemas = openApiSchema?.components?.schemas ?? {};
  const names = Object.keys(schemas);
  const invalidNames = names.filter((name) => !isTypeIdentifier(name));
  if (invalidNames.length > 0) {
    throw new Error(
      `OpenAPI schema names are not valid TypeScript identifiers: ${invalidNames.join(", ")}`,
    );
  }

  return (
    HEADER +
    `import type { components } from "./generated-types";\n\n` +
    names
      .map((name) => `export type ${name} = components["schemas"]["${name}"];`)
      .join("\n") +
    "\n"
  );
}

async function loadOpenApiDocument(schema) {
  if (schema.protocol === "file:") {
    return JSON.parse(readFileSync(fileURLToPath(schema), "utf8"));
  }

  const response = await fetch(schema);
  if (!response.ok) {
    throw new Error(`Failed to fetch OpenAPI schema: ${response.status}`);
  }
  return response.json();
}

function safeWrite(path, content) {
  try {
    const stat = lstatSync(path);
    if (stat.isSymbolicLink()) {
      unlinkSync(path);
    }
  } catch (e) {
    // Ignore error if file doesn't exist
  }
  writeFileSync(path, content);
}

export async function main(argv = process.argv) {
  const [, , argSchema, argOutput, argTypesOutput] = argv;
  const schemaSource = argSchema ?? process.env.GLAZE_SCHEMA_SOURCE;
  const schema = schemaSource
    ? pathToFileURL(resolvePath(schemaSource))
    : new URL("http://localhost:8080/api/schema/?format=json");
  
  const rawOutputPath =
    argOutput ??
    process.env.GLAZE_OUTPUT_PATH ??
    "src/util/generated-types.ts";
  const outputPath = resolvePath(rawOutputPath);

  const rawTypesOutputPath =
    argTypesOutput ??
    process.env.GLAZE_TYPES_OUTPUT_PATH ??
    "src/util/types.ts";
  const typesOutputPath = resolvePath(rawTypesOutputPath);

  const DATE_NODE = ts.factory.createTypeReferenceNode(
    ts.factory.createIdentifier("Date"),
  );

  const ast = await openapiTS(schema, {
    transform(schemaObject) {
      if (schemaObject.format === "date-time") {
        return DATE_NODE;
      }
    },
  });

  safeWrite(outputPath, HEADER + astToString(ast));
  console.log(`✔ Generated ${outputPath}`);

  const openApiSchema = await loadOpenApiDocument(schema);
  safeWrite(typesOutputPath, renderSchemaAliasModule(openApiSchema));
  console.log(`✔ Generated ${typesOutputPath}`);
}

const invokedAsScript =
  process.argv[1] &&
  pathToFileURL(resolve(process.argv[1])).href === import.meta.url;

if (invokedAsScript) {
  main().catch((error) => {
    console.error(
      error instanceof Error ? (error.stack ?? error.message) : String(error),
    );
    process.exit(1);
  });
}
