/**
 * Generates TypeScript types from the live OpenAPI schema.
 *
 * Requires the Django backend to be running on port 8080.
 * Run via: npm run generate-types
 *
 * Transforms applied on top of the raw schema:
 *   - format: date-time  →  Date  (Axios delivers strings; api.ts converts at runtime)
 */

import openapiTS, { astToString } from 'openapi-typescript'
import ts from 'typescript'
import { writeFileSync } from 'fs'

const SCHEMA_URL = new URL('http://localhost:8080/api/schema/?format=json')
const OUTPUT_PATH = 'src/generated-types.ts'

const HEADER = `\
/**
 * This file was auto-generated by openapi-typescript.
 * Run \`npm run generate-types\` (with Django running on port 8080) to regenerate.
 * DO NOT EDIT BY HAND.
 */

`

const DATE_NODE = ts.factory.createTypeReferenceNode(ts.factory.createIdentifier('Date'))

const ast = await openapiTS(SCHEMA_URL, {
  transform(schemaObject) {
    if (schemaObject.format === 'date-time') {
      return DATE_NODE
    }
  },
})

writeFileSync(OUTPUT_PATH, HEADER + astToString(ast))
console.log(`✔ Generated ${OUTPUT_PATH}`)
