apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: alloy
  namespace: monitoring
  labels:
    app: alloy
spec:
  selector:
    matchLabels:
      app: alloy
  template:
    metadata:
      labels:
        app: alloy
    spec:
      serviceAccountName: alloy
      hostPID: true
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: alloy
          image: grafana/alloy:v1.9.2
          args:
            - run
            - /etc/alloy/config.alloy
            - --storage.path=/var/lib/alloy/data
          env:
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: GRAFANA_CLOUD_PROM_USERNAME
              valueFrom:
                secretKeyRef:
                  name: alloy-grafana-cloud
                  key: GRAFANA_CLOUD_PROM_USERNAME
            - name: GRAFANA_CLOUD_PROM_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alloy-grafana-cloud
                  key: GRAFANA_CLOUD_PROM_PASSWORD
            - name: GRAFANA_CLOUD_PROM_URL
              valueFrom:
                secretKeyRef:
                  name: alloy-grafana-cloud
                  key: GRAFANA_CLOUD_PROM_URL
            - name: GRAFANA_CLOUD_LOKI_USERNAME
              valueFrom:
                secretKeyRef:
                  name: alloy-grafana-cloud
                  key: GRAFANA_CLOUD_LOKI_USERNAME
            - name: GRAFANA_CLOUD_LOKI_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alloy-grafana-cloud
                  key: GRAFANA_CLOUD_LOKI_PASSWORD
            - name: GRAFANA_CLOUD_LOKI_URL
              valueFrom:
                secretKeyRef:
                  name: alloy-grafana-cloud
                  key: GRAFANA_CLOUD_LOKI_URL
          ports:
            - name: http-metrics
              containerPort: 12345
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "150Mi"
            limits:
              memory: "256Mi"
          volumeMounts:
            - name: config
              mountPath: /etc/alloy
            - name: storage
              mountPath: /var/lib/alloy/data
      volumes:
        - name: config
          configMap:
            name: alloy-config
        - name: storage
          emptyDir: {}
