apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alloy-grafana-cloud
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: alloy-grafana-cloud
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_CLOUD_PROM_USERNAME
      remoteRef:
        key: GRAFANA_CLOUD_PROM_USERNAME
    - secretKey: GRAFANA_CLOUD_PROM_PASSWORD
      remoteRef:
        key: GRAFANA_CLOUD_PROM_PASSWORD
    - secretKey: GRAFANA_CLOUD_LOKI_USERNAME
      remoteRef:
        key: GRAFANA_CLOUD_LOKI_USERNAME
    - secretKey: GRAFANA_CLOUD_LOKI_PASSWORD
      remoteRef:
        key: GRAFANA_CLOUD_LOKI_PASSWORD
    - secretKey: GRAFANA_CLOUD_PROM_URL
      remoteRef:
        key: GRAFANA_CLOUD_PROM_URL
    - secretKey: GRAFANA_CLOUD_LOKI_URL
      remoteRef:
        key: GRAFANA_CLOUD_LOKI_URL
