apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  repo: https://charts.jetstack.io
  chart: cert-manager
  version: "v1.20.2"
  targetNamespace: cert-manager
  createNamespace: true
  valuesContent: |-
    crds:
      enabled: true
    extraEnv:
      - name: GOGC
        value: "25"
      - name: GOMEMLIMIT
        value: "45MiB"
    resources:
      requests:
        cpu: "10m"
        memory: "32Mi"
      limits:
        memory: "64Mi"
    cainjector:
      extraEnv:
        - name: GOGC
          value: "25"
        - name: GOMEMLIMIT
          value: "45MiB"
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
        limits:
          memory: "64Mi"
    webhook:
      extraEnv:
        - name: GOGC
          value: "25"
        - name: GOMEMLIMIT
          value: "45MiB"
      livenessProbe:
        timeoutSeconds: 5
      readinessProbe:
        timeoutSeconds: 5
      resources:
        requests:
          cpu: "10m"
          memory: "32Mi"
        limits:
          memory: "64Mi"
