---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            namespace: default
            key: clientId
          clientSecret:
            name: infisical-auth
            namespace: default
            key: clientSecret
      secretsScope:
        projectSlug: "potter-doc-d-a-xh"
        environmentSlug: "prod"
        recursive: false
