---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: tailscale-operator-values
spec:
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: tailscale
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: infisical
      kind: ClusterSecretStore
    target:
      name: tailscale-operator-values
      creationPolicy: Owner
      template:
        engineVersion: v2
        data:
          oauth: |-
            oauth:
              clientId: {{ .clientId | quote }}
              clientSecret: {{ .clientSecret | quote }}
    data:
      - secretKey: clientId
        remoteRef:
          key: TAILSCALE_OAUTH_CLIENT_ID
      - secretKey: clientSecret
        remoteRef:
          key: TAILSCALE_OAUTH_CLIENT_SECRET
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  repo: https://pkgs.tailscale.com/helmcharts
  chart: tailscale-operator
  targetNamespace: tailscale
  createNamespace: true
  valuesSecrets:
    - name: tailscale-operator-values
      keys:
        - oauth
