---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik-crd
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-crd-39.0.701+up39.0.7.tgz
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: traefik
  namespace: kube-system
spec:
  chart: https://%{KUBERNETES_API}%/static/charts/traefik-39.0.701+up39.0.7.tgz
  set:
    global.systemDefaultRegistry: ""
  valuesContent: |-
    deployment:
      podAnnotations:
        prometheus.io/port: "8082"
        prometheus.io/scrape: "true"
    providers:
      kubernetesIngress:
        publishedService:
          enabled: true
    priorityClassName: "system-cluster-critical"
    image:
      repository: "rancher/mirrored-library-traefik"
      tag: "3.6.13"
    tolerations:
    - key: "CriticalAddonsOnly"
      operator: "Exists"
    - key: "node-role.kubernetes.io/control-plane"
      operator: "Exists"
      effect: "NoSchedule"
    service:
      type: "LoadBalancer"
      ipFamilyPolicy: "PreferDualStack"
      additionalServices:
        tailscale:
          type: "LoadBalancer"
          annotations:
            external-dns.alpha.kubernetes.io/hostname: "admin.potterdoc.com,headlamp.potterdoc.com"
            tailscale.com/proxy-class: "default"
          spec:
            loadBalancerClass: "tailscale"
            allocateLoadBalancerNodePorts: false
    ports:
      websecure:
        expose:
          default: true
          tailscale: false
      websecure-tailscale:
        port: 9443
        exposedPort: 443
        expose:
          default: false
          tailscale: true
        http:
          tls:
            enabled: true
    resources:
      requests:
        cpu: "50m"
        memory: "64Mi"
      limits:
        memory: "80Mi"
    updateStrategy:
      type: "RollingUpdate"
      rollingUpdate:
        maxUnavailable: 0
        maxSurge: 1
