export const SMALL_TUTORIAL_INLAY_PLACEMENTS = {
  LEFT: "left",
  RIGHT: "right",
  TOP: "top",
} as const;

export type SmallTutorialInlayPlacement =
  (typeof SMALL_TUTORIAL_INLAY_PLACEMENTS)[keyof typeof SMALL_TUTORIAL_INLAY_PLACEMENTS];

export const SMALL_TUTORIAL_INLAY_RIGHT_POSITIONING = {
  TAIL_PROTRUSION_PX: 6,
  MIN_LEFT_EDGE_GAP_PX: 4,
} as const;

export const SMALL_TUTORIAL_INLAY_RIGHT_HORIZONTAL_OFFSET_PX =
  SMALL_TUTORIAL_INLAY_RIGHT_POSITIONING.TAIL_PROTRUSION_PX +
  SMALL_TUTORIAL_INLAY_RIGHT_POSITIONING.MIN_LEFT_EDGE_GAP_PX;

export const SMALL_TUTORIAL_INLAY_LEFT_HORIZONTAL_OFFSET_PX =
  SMALL_TUTORIAL_INLAY_RIGHT_HORIZONTAL_OFFSET_PX;

export const SMALL_TUTORIAL_INLAY_TOP_POSITIONING = {
  TAIL_PROTRUSION_PX: 6,
  MIN_TOP_EDGE_GAP_PX: 4,
} as const;

export const SMALL_TUTORIAL_INLAY_TOP_VERTICAL_OFFSET_PX =
  SMALL_TUTORIAL_INLAY_TOP_POSITIONING.TAIL_PROTRUSION_PX +
  SMALL_TUTORIAL_INLAY_TOP_POSITIONING.MIN_TOP_EDGE_GAP_PX;
