apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glaze.fullname" . }}-otel-config
  labels:
    {{- include "glaze.labels" . | nindent 4 }}
data:
  otel-collector-config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: 0.0.0.0:4317
          http:
            endpoint: 0.0.0.0:4318

    extensions:
      basicauth/grafana_cloud:
        client_auth:
          username: ${env:GRAFANA_CLOUD_INSTANCE_ID}
          password: ${env:GRAFANA_CLOUD_OTLP_TOKEN}

    exporters:
      otlphttp/grafana_cloud:
        endpoint: https://otlp-gateway-prod-us-east-3.grafana.net/otlp
        auth:
          authenticator: basicauth/grafana_cloud

    service:
      extensions: [basicauth/grafana_cloud]
      pipelines:
        traces:
          receivers: [otlp]
          exporters: [otlphttp/grafana_cloud]
        logs:
          receivers: [otlp]
          exporters: [otlphttp/grafana_cloud]
        metrics:
          receivers: [otlp]
          exporters: [otlphttp/grafana_cloud]
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glaze.fullname" . }}-env
  labels:
    {{- include "glaze.labels" . | nindent 4 }}
data:
  REDIS_CACHE_URL: "redis://{{ include "glaze.fullname" . }}-redis:6379/1"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://{{ include "glaze.fullname" . }}-otelcol:4317"
  OTEL_RESOURCE_ATTRIBUTES: "service.name=glaze"
  PRODUCTION: "true"
  ALLOWED_HOST: {{ .Values.appConfig.allowedHost | quote }}
  APP_ORIGIN: {{ .Values.appConfig.appOrigin | quote }}
  INVITE_LINK_BASE_URL: {{ .Values.appConfig.inviteLinkBaseUrl | quote }}
  GOOGLE_OAUTH_CLIENT_ID: {{ .Values.appConfig.googleOauthClientId | quote }}
  ADMIN_URL: {{ .Values.appConfig.adminUrl | quote }}
  {{- if .Values.adminIngress.enabled }}
  ADMIN_INGRESS_HOST: {{ .Values.adminIngress.host | quote }}
  {{- end }}
  R2_ACCOUNT_ID: {{ .Values.appConfig.r2AccountId | quote }}
  R2_BUCKET_NAME: {{ .Values.appConfig.r2BucketName | quote }}
  R2_PUBLIC_URL: {{ .Values.appConfig.r2PublicUrl | quote }}
  {{- with .Values.appConfig.emailHost }}
  EMAIL_HOST: {{ . | quote }}
  {{- end }}
  {{- with .Values.appConfig.emailPort }}
  EMAIL_PORT: {{ . | quote }}
  {{- end }}
  {{- with .Values.appConfig.emailHostUser }}
  EMAIL_HOST_USER: {{ . | quote }}
  {{- end }}
  {{- with .Values.appConfig.emailUseSsl }}
  EMAIL_USE_SSL: {{ . | quote }}
  {{- end }}
  {{- with .Values.appConfig.defaultFromEmail }}
  DEFAULT_FROM_EMAIL: {{ . | quote }}
  {{- end }}
  {{- with .Values.appConfig.remoteRembgUrl }}
  REMOTE_REMBG_URL: {{ . | quote }}
  {{- end }}
  {{- with .Values.appConfig.otelEnabled }}
  OTEL_ENABLED: {{ . | quote }}
  {{- end }}
