{{- if .Values.adminIngress.enabled -}}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ include "glaze.fullname" . }}-cloudflare-token
  labels:
    {{- include "glaze.labels" . | nindent 4 }}
spec:
  namespaceSelectors:
    - matchLabels:
        kubernetes.io/metadata.name: cert-manager
  refreshTime: 1h
  externalSecretSpec:
    refreshInterval: 1h
    secretStoreRef:
      name: infisical
      kind: ClusterSecretStore
    target:
      name: cloudflare-api-token
      creationPolicy: Owner
    data:
      - secretKey: api-token
        remoteRef:
          key: CLOUDFLARE_API_TOKEN
{{- end }}
