apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "glaze.fullname" . }}-deploy-init
  labels:
    {{- include "glaze.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded,hook-failed
spec:
  backoffLimit: 3
  template:
    metadata:
      name: {{ include "glaze.fullname" . }}-deploy-init
      labels:
        {{- include "glaze.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: deploy-init
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - python
            - manage.py
            - deploy_init
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: glaze-secrets
                  key: POSTGRES_PASSWORD
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: glaze-secrets
                  key: SECRET_KEY
            - name: DATABASE_URL
              value: "postgres://{{ .Values.postgres.user }}:$(POSTGRES_PASSWORD)@{{ include "glaze.fullname" . }}-postgres:5432/{{ .Values.postgres.database }}"
            - name: REDIS_CACHE_URL
              value: "redis://{{ include "glaze.fullname" . }}-redis:6379/1"
