{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "glaze.fullname" . }}-security-headers
  labels:
    {{- include "glaze.labels" . | nindent 4 }}
spec:
  headers:
    contentSecurityPolicy: >-
      default-src 'self';
      script-src 'self' https://accounts.google.com https://apis.google.com https://upload-widget.cloudinary.com;
      style-src 'self' 'unsafe-inline' https://accounts.google.com https://fonts.googleapis.com;
      img-src 'self' data: https://res.cloudinary.com;
      connect-src 'self' https://api.cloudinary.com;
      font-src 'self' https://fonts.gstatic.com;
      frame-src https://accounts.google.com https://widget.cloudinary.com https://upload-widget.cloudinary.com;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
{{- end }}
