apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infisical
  labels:
    {{- include "glaze.labels" . | nindent 4 }}
spec:
  provider:
    infisical:
      auth:
        universalAuthCredentials:
          clientId:
            name: infisical-auth
            namespace: {{ .Release.Namespace }}
            key: clientId
          clientSecret:
            name: infisical-auth
            namespace: {{ .Release.Namespace }}
            key: clientSecret
      secretsScope:
        projectSlug: {{ .Values.infisical.projectSlug | quote }}
        environmentSlug: "prod"
        recursive: false
