# ruff: noqa: F401
import hashlib
import json
import os
import re
from collections import defaultdict
from typing import Callable

from django.apps import apps
from django.conf import settings
from django.contrib.auth import authenticate, get_user_model, login, logout
from django.db.models import DateTimeField, OuterRef, Q, Subquery
from django.db.models.functions import Coalesce, Greatest
from django.http import StreamingHttpResponse
from django.shortcuts import get_object_or_404
from django.views.decorators.csrf import ensure_csrf_cookie
from drf_spectacular.utils import OpenApiParameter, extend_schema, inline_serializer
from google.auth.transport import requests as google_requests
from google.oauth2 import id_token as google_id_token
from rest_framework import serializers as drf_serializers
from rest_framework import status
from rest_framework.decorators import api_view, parser_classes, permission_classes
from rest_framework.parsers import FormParser, MultiPartParser
from rest_framework.permissions import AllowAny, IsAdminUser, IsAuthenticated
from rest_framework.request import Request
from rest_framework.response import Response

from backend.otel import traced

from .models import (
    AsyncTask,
    FavoriteGlazeCombination,
    GlazeCombination,
    Piece,
    PieceState,
    UserProfile,
)
from .serializer_registry import (
    _GLOBAL_ENTRY_SERIALIZERS,  # auto-generated in _register_globals(); hand-written serializers overwrite
)
from .serializers import (
    AsyncTaskSerializer,
    AuthUserSerializer,
    GlazeCombinationImageEntrySerializer,
    GoogleAuthSerializer,
    LoginSerializer,
    PieceCreateSerializer,
    PieceDetailSerializer,
    PieceStateCreateSerializer,
    PieceStateSerializer,
    PieceStateUpdateSerializer,
    PieceSummarySerializer,
    PieceUpdateSerializer,
    RegisterSerializer,
    TaskSubmissionSerializer,
)
from .utils import bootstrap_dev_user
from .workflow import (
    get_glaze_image_qualifying_states,
    get_global_model_and_field,
    is_private_global,
    is_public_global,
)

_HEX_COLOR_RE = re.compile(r"^#([0-9a-fA-F]{3,4}|[0-9a-fA-F]{6}|[0-9a-fA-F]{8})$")


def _apply_global_filters(qs, model_cls, request):
    """Apply query-param filters declared in a model's ``filterable_fields`` dict.

    Each entry in ``filterable_fields`` has the form::

        'field_lookup': {'type': 'boolean' | 'm2m_id' | 'fk_id', 'param': 'query_param_name'}

    ``param`` defaults to the field lookup key when omitted.

    - ``boolean``: ?param=true|false → filter(**{lookup: True|False})
    - ``m2m_id``: ?param=id1,id2,... → successive filters so ALL ids must match
    - ``fk_id``: ?param=<pk> → exact FK match (filter(**{lookup: pk}))
    """
    filterable = getattr(model_cls, "filterable_fields", {})
    for lookup, meta in filterable.items():
        param = meta.get("param", lookup)
        filter_type = meta.get("type", "boolean")
        raw = request.query_params.get(param, "").strip()
        if not raw:
            continue
        if filter_type == "boolean":
            if raw.lower() == "true":
                qs = qs.filter(**{lookup: True})
            elif raw.lower() == "false":
                qs = qs.filter(**{lookup: False})
        elif filter_type == "m2m_id":
            for pk in (s.strip() for s in raw.split(",") if s.strip()):
                qs = qs.filter(**{lookup: pk})
        elif filter_type == "fk_id":
            qs = qs.filter(**{lookup: raw})
    return qs


# Map from global model class → its corresponding Favorite* model class.
# The Favorite* model must declare global_fk_field and get_favorite_ids_for().
_FAVORITES_REGISTRY = {
    GlazeCombination: FavoriteGlazeCombination,
}


_GLOBAL_ENTRY_SCHEMA = {
    "type": "object",
    "properties": {
        "id": {"type": "string"},
        "name": {"type": "string"},
        "is_public": {"type": "boolean"},
    },
    "required": ["id", "name", "is_public"],
}

_GLOBAL_CREATE_REQUEST_SCHEMA = {
    "application/json": {
        "type": "object",
        "properties": {
            "field": {"type": "string"},
            "value": {"type": "string"},
        },
        "required": ["field", "value"],
    }
}


@traced
def _global_entries_impl(request: Request, global_name: str) -> Response:
    """Core implementation for GET/POST /api/globals/<global_name>/.

    Called by the per-global views generated by make_global_entry_view(); not
    a view itself.  The caller's extend_schema annotation owns the OpenAPI
    description for each specific global type.
    """
    model_cls, fields, display_field = get_global_model_and_field(global_name)
    has_public_library = is_public_global(global_name)

    if request.method == "GET":
        if has_public_library:
            # Return both the user's private objects and all public objects (user IS NULL).
            base_qs = model_cls.objects.filter(
                Q(user=request.user) | Q(user__isnull=True)
            )
        else:
            base_qs = model_cls.objects.filter(user=request.user)

        # Apply query-param filters for models that declare filterable_fields.
        base_qs = _apply_global_filters(base_qs, model_cls, request)

        # Use a richer serializer if one is registered for this model.
        entry_serializer_cls = _GLOBAL_ENTRY_SERIALIZERS.get(model_cls)
        if entry_serializer_cls is not None:
            fav_model = _FAVORITES_REGISTRY.get(model_cls)
            favorite_ids = (
                fav_model.get_favorite_ids_for(request.user) if fav_model else set()
            )
            prepare_queryset = getattr(
                entry_serializer_cls, "prepare_global_entry_queryset", None
            )
            if callable(prepare_queryset):
                objects = list(prepare_queryset(base_qs, display_field))
            else:
                objects = list(base_qs.order_by(display_field))
            return Response(
                entry_serializer_cls(
                    objects,
                    many=True,
                    context={"request": request, "favorite_ids": favorite_ids},
                ).data
            )

        # Default: lightweight {id, name, is_public} response.
        # If the display field is a relation (FK), use select_related for efficient
        # loading and stringify the value; otherwise use only() for efficiency.
        try:
            display_field_meta = model_cls._meta.get_field(display_field)
            display_is_relation = getattr(display_field_meta, "is_relation", False)
        except Exception:
            display_is_relation = False

        if display_is_relation:
            objects = base_qs.select_related(display_field).order_by(display_field)
        else:
            objects = base_qs.only("pk", display_field).order_by(display_field)

        return Response(
            [
                {
                    "id": str(obj.pk),
                    "name": str(getattr(obj, display_field)),
                    "is_public": obj.user_id is None,
                }
                for obj in objects
            ]
        )

    if not is_private_global(global_name):
        return Response(
            {"detail": "Private instances of this type are not supported."},
            status=status.HTTP_405_METHOD_NOT_ALLOWED,
        )

    # Models with ordered M2M relations declare get_or_create_from_ordered_pks.
    if hasattr(model_cls, "get_or_create_from_ordered_pks"):
        pks = request.data.get("layers")
        if not pks or not isinstance(pks, list):
            return Response(
                {"detail": "layers must be a non-empty list of PKs."},
                status=status.HTTP_400_BAD_REQUEST,
            )
        try:
            obj, created = model_cls.get_or_create_from_ordered_pks(
                user=request.user, pks=pks
            )
        except ValueError as exc:
            return Response({"detail": str(exc)}, status=status.HTTP_400_BAD_REQUEST)
        status_code = status.HTTP_201_CREATED if created else status.HTTP_200_OK
        return Response(
            {"id": str(obj.pk), "name": obj.name, "is_public": obj.user_id is None},
            status=status_code,
        )

    field = request.data.get("field")
    value = request.data.get("value")
    values = request.data.get("values")
    if values is not None and not isinstance(values, dict):
        return Response(
            {"detail": "values must be an object."}, status=status.HTTP_400_BAD_REQUEST
        )

    payload = dict(values or {})
    if field:
        if field not in fields:
            return Response(
                {"detail": "Invalid field"}, status=status.HTTP_400_BAD_REQUEST
            )
        payload[field] = value

    allowed_fields = {
        field_name
        for field_name, field_def in fields.items()
        if "$ref" not in field_def
    }
    unknown_fields = sorted(set(payload) - allowed_fields)
    if unknown_fields:
        return Response(
            {"detail": f"Invalid field: {unknown_fields[0]}"},
            status=status.HTTP_400_BAD_REQUEST,
        )
    if not payload.get(display_field):
        return Response(
            {"detail": "Value is required"}, status=status.HTTP_400_BAD_REQUEST
        )

    for field_name, field_val in payload.items():
        field_def = fields.get(field_name, {})
        if field_def.get("format") == "hex_color" and field_val is not None:
            if not _HEX_COLOR_RE.match(str(field_val)):
                return Response(
                    {
                        "detail": f"{field_name} must be a valid hex color code (e.g. #rgb or #rrggbb)."
                    },
                    status=status.HTTP_400_BAD_REQUEST,
                )

    lookup = {"user": request.user, display_field: payload[display_field]}
    defaults = {key: val for key, val in payload.items() if key != display_field}
    obj, created = model_cls.objects.get_or_create(**lookup, defaults=defaults)
    status_code = status.HTTP_201_CREATED if created else status.HTTP_200_OK
    entry_serializer_cls = _GLOBAL_ENTRY_SERIALIZERS.get(model_cls)
    if entry_serializer_cls is not None:
        return Response(
            entry_serializer_cls(
                obj, context={"request": request, "favorite_ids": set()}
            ).data,
            status=status_code,
        )
    return Response(
        {"id": str(obj.pk), "name": getattr(obj, display_field)}, status=status_code
    )


def make_global_entry_view(global_name: str):
    """Return a fully-annotated view function for the given global type.

    The GET response schema is derived from _GLOBAL_ENTRY_SERIALIZERS: globals
    with a registered serializer get that serializer's schema; all others get
    the generic {id, name, is_public} schema.  This means extend_schema accuracy
    is mechanically guaranteed by the same registry that drives view behavior —
    adding a richer serializer for a new global requires only one registry entry.
    """
    model_cls, _, _ = get_global_model_and_field(global_name)
    entry_serializer_cls = _GLOBAL_ENTRY_SERIALIZERS.get(model_cls)

    get_responses: dict = (
        {200: entry_serializer_cls(many=True)}
        if entry_serializer_cls is not None
        else {200: {"type": "array", "items": _GLOBAL_ENTRY_SCHEMA}}
    )

    @extend_schema(responses=get_responses, methods=["GET"])
    @extend_schema(
        request=_GLOBAL_CREATE_REQUEST_SCHEMA,
        responses={200: _GLOBAL_ENTRY_SCHEMA, 201: _GLOBAL_ENTRY_SCHEMA},
        methods=["POST"],
    )
    @api_view(["GET", "POST"])
    @permission_classes([IsAuthenticated])
    def view(request: Request) -> Response:
        return _global_entries_impl(request, global_name)

    view.__name__ = f"global_entries_{global_name}"  # type: ignore[attr-defined]
    view.__qualname__ = f"global_entries_{global_name}"  # type: ignore[attr-defined]
    return view


@traced
def _global_entry_favorite_impl(
    request: Request, model_cls, fav_model_cls, pk: str
) -> Response:
    """Core implementation for POST/DELETE /api/globals/<global_name>/<pk>/favorite/.

    model_cls is the global's Django model; fav_model_cls is its Favorite* model.
    Called by views generated by make_global_entry_favorite_view(); not a view itself.
    """
    obj = get_object_or_404(model_cls, pk=pk)
    # Users may only favorite entries visible to them (public or their own).
    if obj.user_id is not None and obj.user_id != request.user.pk:
        return Response(status=status.HTTP_404_NOT_FOUND)

    fk_field = fav_model_cls.global_fk_field
    if request.method == "POST":
        fav_model_cls.objects.get_or_create(user=request.user, **{fk_field: obj})
    else:
        fav_model_cls.objects.filter(user=request.user, **{fk_field: obj}).delete()

    return Response(status=status.HTTP_204_NO_CONTENT)


def make_global_entry_favorite_view(global_name: str):
    """Return an annotated POST/DELETE favorite-toggle view for the given global.

    Only called for globals whose model is in _FAVORITES_REGISTRY; the URL is only
    registered for those globals, so non-favoritable types return 404 (no route)
    rather than 405.
    """
    model_cls, _, _ = get_global_model_and_field(global_name)
    fav_model_cls = _FAVORITES_REGISTRY[model_cls]

    @extend_schema(methods=["POST"], request=None, responses={204: None, 404: None})
    @extend_schema(methods=["DELETE"], request=None, responses={204: None, 404: None})
    @api_view(["POST", "DELETE"])
    @permission_classes([IsAuthenticated])
    def view(request: Request, pk: str) -> Response:
        return _global_entry_favorite_impl(request, model_cls, fav_model_cls, pk)

    view.__name__ = f"global_entry_favorite_{global_name}"  # type: ignore[attr-defined]
    view.__qualname__ = f"global_entry_favorite_{global_name}"  # type: ignore[attr-defined]
    return view
